String policyText="""
<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=Generator content="Microsoft Word 15 (filtered)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Roboto;
	panose-1:2 0 0 0 0 0 0 0 0 0;}
@font-face
	{font-family:"var\(--list--font-family\)";
	panose-1:0 0 0 0 0 0 0 0 0 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0in;
	margin-right:0in;
	margin-bottom:8.0pt;
	margin-left:0in;
	line-height:107%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
.MsoChpDefault
	{font-family:"Calibri",sans-serif;}
.MsoPapDefault
	{margin-bottom:8.0pt;
	line-height:107%;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
 /* List Definitions */
 ol
	{margin-bottom:0in;}
ul
	{margin-bottom:0in;}
-->
</style>

</head>

<body lang=EN-US style='word-wrap:break-word'>

<div class=WordSection1>

<p class=MsoNormal style='background:white'><b><span style='font-size:37.5pt;
font-family:"Arial",sans-serif;color:black'>Privacy Policy</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>MySundayNotes We are committed to protecting your privacy. This Privacy Policy<br>
explains how your personal information is collected, used, and disclosed by MySundayNotes.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>This Privacy Policy applies to our website, and its associated subdomains
(collectively, our “Service”) alongside our application,<br>
My SundayNotes. By accessing or using our Service, you signify that you have
read, understood, and agree to our collection,<br>
storage, use, and disclosure of your personal information as described in this
Privacy Policy and our Terms of Service.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Definitions and key terms</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Cookie:
small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Company:
When this policy mentions “Company,” “we,” “us,” or “our,” it refers to MySundayNotes, which is responsible for your information under this Privacy Policy.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Country:
where My SundayNotes or the owners/founders of My SundayNotes are based, in this case, is united States of America</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Customer:
refers to the company, organization or person that signs up to use the MySundayNotes Service to manage the relationships with your consumers or service
users.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Device: any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit My SundayNotes and use the services.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>IP address:
Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Personnel:
refers to those individuals who are employed by My SundayNotes or are under
contract to perform a service on behalf of one of the parties.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Personal
Data: any information that directly, indirectly, or in connection with other
information — including a personal identification number — allows for the
identification or identifiability of a natural person.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Service:
refers to the service provided by My SundayNotes as described in the relative
terms (if available) and on this platform.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Third-party
service: refers to advertisers, contest sponsors, promotional and marketing
partners, and others who provide our content or whose products or services we
think may interest you.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Website: MySundayNotes’s site, which can be accessed via this URL: mysundaynotes.com</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>You: a person or entity that is registered with My SundayNotes to use the Services.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>What Information Do We Collect?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We collect
information from you when you visit our website, register on our site, place an
order, subscribe to our newsletter, respond to a survey or fill out a form.</span></p>

<ul style='margin-top:0in' type=disc>
 <li class=MsoNormal style='color:black;margin-bottom:0in;line-height:normal;
     background:white'><span style='font-size:12.0pt;font-family:"var(--list--font-family)",serif'>Name
     Username</span></li>
</ul>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>&nbsp;</span></p>

<ul style='margin-top:0in' type=disc>
 <li class=MsoNormal style='color:black;margin-bottom:0in;line-height:normal;
     background:white'><span style='font-size:12.0pt;font-family:"var(--list--font-family)",serif'>Phone
     Numbers</span></li>
</ul>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>&nbsp;</span></p>

<ul style='margin-top:0in' type=disc>
 <li class=MsoNormal style='color:black;margin-bottom:0in;line-height:normal;
     background:white'><span style='font-size:12.0pt;font-family:"var(--list--font-family)",serif'>Email
     Addresses</span></li>
</ul>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>When Does My SundayNotes use end-user information from
third parties?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>MySundayNotes will collect End User Data necessary to provide the My SundayNotes
services to our customers. End-users may voluntarily provide us with the
information they have made available on social media websites. If you provide
us with any such information, we may collect publicly available information
from the social media websites you have indicated. You can control how much of
your information social media websites make public by visiting these websites and
changing your privacy settings.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>When does My SundayNotes use customer information from
third parties?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We receive
some information from the third parties when you contact us. For example, when
you submit your email address to us to show interest in becoming a MySundayNotes customer, we receive information from a third party that provides
automated fraud detection services to My SundayNotes. We also occasionally
collect information that is made publicly available on social media websites.
You can control how much of your information social media websites make public
by visiting these websites and changing your privacy settings.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Do we share the information we collect with third
parties?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We may share the information that we collect, both personal and non-personal, with
third parties such as advertisers, contest sponsors, promotional and marketing
partners, and others who provide our content or whose products or services we
think may interest you. We may also share it with our current and future
affiliated companies and business partners, and if we are involved in a merger,
asset sale, or other business reorganization, we may also share or transfer
your personal and non-personal information to our successors-in-interest.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We may engage trusted third-party service providers to perform functions and provide
services to us, such as hosting and maintaining our servers and the website,
database storage and management, e-mail management, storage marketing, credit
card processing, customer service, and fulfilling orders for products and
services you may purchase through the website. We will likely share your
personal information, and possibly some non-personal information, with these
third parties to enable them to perform these services for us and for you.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We may share portions of our log file data, including IP addresses, for analytics purposes
with third parties such as web analytics partners, application developers, and
ad networks. If your IP address is shared, it may be used to estimate general
location and other technographics such as connection speed, whether you have
visited the website in a shared location, and the type of the device used to
visit the website. They may aggregate information about our advertising and
what you see on the website and then provide auditing, research and reporting
for us and our advertisers.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We may also disclose personal and non-personal information about you to government or law
enforcement officials or private parties as we, in our sole discretion, believe
necessary or appropriate in order to respond to claims, legal process
(including subpoenas), to protect our rights and interests or those of a third
party, the safety of the public or any person, to prevent or stop any illegal,
unethical, or legally actionable activity, or to otherwise comply with
applicable court orders, laws, rules, and regulations.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Where and when is information collected from customers and end-users?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>MySundayNotes will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>How Do We Use The Information We Collect?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Any of the information we collect from you may be used in one of the following ways:</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>To personalize your experience (your information helps us to better respond to
your individual needs)</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>To improve our website (we continually strive to improve our website offerings based on
the information and feedback we receive from you)</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>To improve
customer service (your information helps us to more effectively respond to your
customer service requests and support needs)</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>To process
transactions</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>To
administer a contest, promotion, survey, or other site feature</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>To send
periodic emails</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>How Do We Use Your Email Address?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>By
submitting your email address on this website, you agree to receive emails from
us. You can cancel your participation in any of these email lists at any time
by clicking on the opt-out link or other unsubscribe option that is included in
the respective email. We only send emails to people who have authorized us to
contact them, either directly, or through a third party. We do not send
unsolicited commercial emails, because we hate spam as much as you do. By
submitting your email address, you also agree to allow us to use your email
address for customer audience targeting on sites like Facebook, where we
display custom advertising to specific people who have opted-in to receive
communications from us. Email addresses submitted only through the order
processing page will be used for the sole purpose of sending you information
and updates pertaining to your order. If, however, you have provided the same
email to us through another method, we may use it for any of the purposes stated
in this Policy. Note: If at any time you would like to unsubscribe from
receiving future emails, we include detailed unsubscribe instructions at the
bottom of each email.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>How Long Do We Keep Your Information?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We keep
your information only so long as we need it to provide My SundayNotes to you
and fulfill the purposes described in this policy. This is also the case for
anyone that we share your information with and who carries out services on our
behalf. When we no longer need to use your information and there is no need for
us to keep it to comply with our legal or regulatory obligations, we’ll either
remove it from our systems or depersonalize it so that we can’t identify you.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>How Do We Protect Your Information?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We
implement a variety of security measures to maintain the safety of your
personal information when you place an order or enter, submit, or access your
personal information. We offer the use of a secure server. All supplied
sensitive/credit information is transmitted via Secure Socket Layer (SSL)
technology and then encrypted into our Payment gateway providers database only
to be accessible by those authorized with special access rights to such
systems, and are required to keep the information confidential. After a
transaction, your private information (credit cards, social security numbers,
financials, etc.) is never kept on file. We cannot, however, ensure or warrant
the absolute security of any information you transmit to My SundayNotes or
guarantee that your information on the Service may not be accessed, disclosed,
altered, or destroyed by a breach of any of our physical, technical, or
managerial safeguards.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Could my information be transferred to other countries?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>MySundayNotes is incorporated in united state of America. Information collected
via our website, through direct interactions with you, or from use of our help
services may be transferred from time to time to our offices or personnel, or
to third parties, located throughout the world, and may be viewed and hosted
anywhere in the world, including countries that may not have laws of general
applicability regulating the use and transfer of such data. To the fullest
extent allowed by applicable law, by using any of the above, you voluntarily
consent to the trans-border transfer and hosting of such information.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Is the information collected through the My SundayNotes
Service secure?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We take
precautions to protect the security of your information. We have physical,
electronic, and managerial procedures to help safeguard, prevent unauthorized
access, maintain data security, and correctly use your information. However,
neither people nor security systems are foolproof, including encryption
systems. In addition, people can commit intentional crimes, make mistakes or
fail to follow policies. Therefore, while we use reasonable efforts to protect
your personal information, we cannot guarantee its absolute security. If
applicable law imposes any non-disclaimable duty to protect your personal
information, you agree that intentional misconduct will be the standard used to
measure our compliance with that duty.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Can I update or correct my information?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>The rights
you have to request updates or corrections to the information My SundayNotes
collects depend on your relationship with My SundayNotes. Personnel may update
or correct their information as detailed in our internal company employment
policies.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Customers
have the right to request the restriction of certain uses and disclosures of
personally identifiable information as follows. You can contact us in order to
(1) update or correct your personally identifiable information, (2) change your
preferences with respect to communications and other information you receive
from us, or (3) delete the personally identifiable information maintained about
you on our systems (subject to the following paragraph), by cancelling your
account. Such updates, corrections, changes and deletions will have no effect
on other information that we maintain, or information that we have provided to
third parties in accordance with this Privacy Policy prior to such update,
correction, change or deletion. To protect your privacy and security, we may
take reasonable steps (such as requesting a unique password) to verify your
identity before granting you profile access or making corrections. You are
responsible for maintaining the secrecy of your unique password and account
information at all times.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>You should
be aware that it is not technologically possible to remove each and every
record of the information you have provided to us from our system. The need to
back up our systems to protect information from inadvertent loss means that a
copy of your information may exist in a non-erasable form that will be
difficult or impossible for us to locate. Promptly after receiving your
request, all personal information stored in databases we actively use, and
other readily searchable media will be updated, corrected, changed or deleted,
as appropriate, as soon as and to the extent reasonably and technically practicable.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>If you are
an end user and wish to update, delete, or receive any information we have
about you, you may do so by contacting the organization of which you are a
customer.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Governing Law</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>This
Privacy Policy is governed by the laws of united state of America without
regard to its conflict of laws provision. You consent to the exclusive
jurisdiction of the courts in connection with any action or dispute arising
between the parties under or in connection with this Privacy Policy except for
those individuals who may have rights to make claims under Privacy Shield, or
the Swiss-US framework.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>The laws of
united state of America, excluding its conflicts of law rules, shall govern
this Agreement and your use of the website. Your use of the website may also be
subject to other local, state, national, or international laws.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>By using MySundayNotes or contacting us directly, you signify your acceptance of this
Privacy Policy. If you do not agree to this Privacy Policy, you should not
engage with our website, or use our services. Continued use of the website,
direct engagement with us, or following the posting of changes to this Privacy
Policy that do not significantly affect the use or disclosure of your personal
information will mean that you accept those changes.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Your Consent</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We’ve
updated our Privacy Policy to provide you with complete transparency into what
is being set when you visit our site and how it’s being used. By using our MySundayNotes, registering an account, or making a purchase, you hereby consent
to our Privacy Policy and agree to its terms.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><b><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Links to
Other Websites</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>This
Privacy Policy applies only to the Services. The Services may contain links to
other websites not operated or controlled by My SundayNotes. We are not
responsible for the content, accuracy or opinions expressed in such websites,
and such websites are not investigated, monitored or checked for accuracy or
completeness by us. Please remember that when you use a link to go from the
Services to another website, our Privacy Policy is no longer in effect. Your
browsing and interaction on any other website, including those that have a link
on our platform, is subject to that website’s own rules and policies. Such
third parties may use their own cookies or other methods to collect information
about you.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Cookies</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>MySundayNotes uses “Cookies” to identify the areas of our website that you have
visited. A Cookie is a small piece of data stored on your computer or mobile
device by your web browser. We use Cookies to enhance the performance and
functionality of our website but are non-essential to their use. However,
without these cookies, certain functionality like videos may become unavailable
or you would be required to enter your login details every time you visit the
website as we would not be able to remember that you had logged in previously.
Most web browsers can be set to disable the use of Cookies. However, if you
disable Cookies, you may not be able to access functionality on our website
correctly or at all. We never place Personally Identifiable Information in
Cookies.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Blocking and disabling cookies and similar technologies</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><b><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Wherever
you’re located you may also set your browser to block cookies and similar
technologies, but this action may block our essential cookies and prevent our
website from functioning properly, and you may not be able to fully utilize all
of its features and services. You should also be aware that you may also lose
some saved information (e.g. saved login details, site preferences) if you
block cookies on your browser. Different browsers make different controls
available to you. Disabling a cookie or category of cookie does not delete the
cookie from your browser, you will need to do this yourself from within your
browser, you should visit your browser’s help menu for more information.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Kids’ Privacy</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We collect
information from kids under the age of 13 just to better our services. If You
are a parent or guardian and You are aware that Your child has provided Us with
Personal Data without your permission, please contact Us. If We become aware
that We have collected Personal Data from anyone under the age of 13 without
verification of parental consent, We take steps to remove that information from
Our servers.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Changes To Our Privacy Policy</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We may
change our Service and policies, and we may need to make changes to this
Privacy Policy so that they accurately reflect our Service and policies. Unless
otherwise required by law, we will notify you (for example, through our
Service) before we make changes to this Privacy Policy and give you an
opportunity to review them before they go into effect. Then, if you continue to
use the Service, you will be bound by the updated Privacy Policy. If you do not
want to agree to this or any updated Privacy Policy, you can delete your
account.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Third-Party Services</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We may
display, include or make available third-party content (including data,
information, applications and other products services) or provide links to
third-party websites or services (“Third- Party Services”).</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>You
acknowledge and agree that My SundayNotes shall not be responsible for any
Third-Party Services, including their accuracy, completeness, timeliness,
validity, copyright compliance, legality, decency, quality or any other aspect
thereof. My SundayNotes does not assume and shall not have any liability or
responsibility to you or any other person or entity for any Third-Party
Services.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Third-Party
Services and links thereto are provided solely as a convenience to you and you
access and use them entirely at your own risk and subject to such third
parties’ terms and conditions.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Tracking Technologies</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Sessions</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>uses
“Sessions” to identify the areas of our website that you have visited. A
Session is a small piece of data stored on your computer or mobile device by
your web browser.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Information about General Data Protection Regulation
(GDPR)</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><b><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We may be
collecting and using information from you if you are from the European Economic
Area (EEA), and in this section of our Privacy Policy we are going to explain
exactly how and why is this data collected, and how we maintain this data under
protection from being replicated or used in the wrong way.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>What is GDPR?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>GDPR is an
EU-wide privacy and data protection law that regulates how EU residents’ data
is protected by companies and enhances the control the EU residents have, over
their personal data.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>The GDPR is
relevant to any globally operating company and not just the EU-based businesses
and EU residents. Our customers’ data is important irrespective of where they
are located, which is why we have implemented GDPR controls as our baseline
standard for all our operations worldwide.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>What is personal data?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Any data
that relates to an identifiable or identified individual. GDPR covers a broad
spectrum of information that could be used on its own, or in combination with
other pieces of information, to identify a person. Personal data extends beyond
a person’s name or email address. Some examples include financial information,
political opinions, genetic data, biometric data, IP addresses, physical
address, sexual orientation, and ethnicity.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>The Data
Protection Principles include requirements such as:</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Personal
data collected must be processed in a fair, legal, and transparent way and
should only be used in a way that a person would reasonably expect.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Personal
data should only be collected to fulfil a specific purpose and it should only
be used for that purpose.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Organizations
must specify why they need the personal data when they collect it.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Personal
data should be held no longer than necessary to fulfil its purpose.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>People
covered by the GDPR have the right to access their own personal data. They can
also request a copy of their data, and that their data be updated, deleted,
restricted, or moved to another organization.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Why is GDPR important?</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>GDPR adds
some new requirements regarding how companies should protect individuals’
personal data that they collect and process. It also raises the stakes for
compliance by increasing enforcement and imposing greater fines for breach.
Beyond these facts it’s simply the right thing to do. At My SundayNotes we
strongly believe that your data privacy is very important and we already have
solid security and privacy practices in place that go beyond the requirements
of this new regulation.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Individual Data Subject’s Rights – Data Access,
Portability and Deletion</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We are
committed to helping our customers meet the data subject rights requirements of
GDPR. My SundayNotes processes or stores all personal data in fully vetted, DPA
compliant vendors. We do store all conversation and personal data for up to 6
years unless your account is deleted. In which case, we dispose of all data in
accordance with our Terms of Service and Privacy Policy, but we will not hold
it longer than 60 days.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We are
aware that if you are working with EU customers, you need to be able to provide
them with the ability to access, update, retrieve and remove personal data. We
got you! We’ve been set up as self service from the start and have always given
you access to your data and your customers data. Our customer support team is
here for you to answer any questions you might have about working with the API.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><b><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>California
Residents</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>The
California Consumer Privacy Act (CCPA) requires us to disclose categories of
Personal Information we collect and how we use it, the categories of sources
from whom we collect Personal Information, and the third parties with whom we
share it, which we have explained above.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We are also
required to communicate information about rights California residents have
under California law. You may exercise the following rights:</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Right to Know
and Access. You may submit a verifiable request for information regarding the:
(1) categories of Personal Information we collect, use, or share; (2) purposes
for which categories of Personal Information are collected or used by us; (3)
categories of sources from which we collect Personal Information; and (4)
specific pieces of Personal Information we have collected about you.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Right to
Equal Service. We will not discriminate against you if you exercise your
privacy rights.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Right to
Delete. You may submit a verifiable request to close your account and we will
delete Personal Information about you that we have collected.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Request
that a business that sells a consumer’s personal data, not sell the consumer’s
personal data.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>If you make
a request, we have one month to respond to you. If you would like to exercise
any of these rights, please contact us.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We do not sell the Personal Information of our users.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>For more information about these rights, please contact us.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>California Online Privacy Protection Act (CalOPPA)</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>CalOPPA
users have the following rights:</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Right to
Know and Access. You may submit a verifiable request for information regarding
the: (1) categories of Personal Information we collect, use, or share; (2)
purposes for which categories of Personal Information are collected or used by
us; (3) categories of sources from which we collect Personal Information; and
(4) specific pieces of Personal Information we have collected about you.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Right to
Equal Service. We will not discriminate against you if you exercise your privacy
rights.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Right to
Delete. You may submit a verifiable request to close your account and we will
delete Personal Information about you that we have collected.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Right to
request that a business that sells a consumer’s personal data, not sell the
consumer’s personal data.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>If you make
a request, we have one month to respond to you. If you would like to exercise
any of these rights, please contact us.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>We do not
sell the Personal Information of our users.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>For more
information about these rights, please contact us.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:24.75pt;background:
white'><b><span style='font-size:22.5pt;font-family:Roboto;color:#4B4848;
letter-spacing:.75pt'>Contact Us</span></b></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Don’t
hesitate to contact us if you have any questions.</span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal;background:white'><span
style='font-size:12.0pt;font-family:"Arial",sans-serif;color:black'>Via
Email:&nbsp;MySundayNotes@gmail.com</span></p>

<p class=MsoNormal>&nbsp;</p>

</div>

</body>

</html>

        """
;